spring.datasource.url=jdbc:postgresql://localhost:5432/vasyerp_task
spring.datasource.username=tanmaysinh
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#spring.data.mongodb.uri=mongodb://localhost:27017/notification_db

app.jwt.secret="PppppppppppppppLLlllllllllllllll"
app.jwt.expiration-minutes= 60

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


app.rabbitmq.notification-exchange= notification.delayed.exchange
app.rabbitmq.notification-queue= notification.queue
app.rabbitmq.notification-routing-key= notification.send
app.rabbitmq.status-exchange= status.exchange
app.rabbitmq.status-queue= status.queue
app.rabbitmq.status-routing-key= contact.status